## The function makeCacheMatrix creates a matrix object that can cache its inverse.
## The function cacheSolve finds the inverse for a matrix represented by a matrix object, generated
##  by a call to the function makeCacheMatrix.

## makeCacheMatrix is a function which takes as its argument a matrix A and it represents the matrix 
## as a matrix object. Technically the function makeCacheMatrix returns a list of four functions: 
## set: This function sets A.
## get: This function gets A.
## setInverse: This function sets B.
## getInverse: This function gets B.
## Where the variable B represents the inverse of the matrix A.

makeCacheMatrix <- function(A = matrix()) {
    B <- NULL   # Initializing B, which represents the inverse of A.
    
    ## the set function assigns a value to A and initializes B
    set <- function(y) {
        A <<- y
        B <<- NULL
    } 
    
    get <- function(){
        A
    }
    
    setInverse <- function(Inverse){
        B <<- Inverse
    }
    getInverse <- function() {
        B
    }
    ## a list of the four functions set, get, setInverse, getInverse is returned 
    ## the element the function set is named set and so on.
    list(set = set, get = get,
         setInverse = setInverse,
         getInverse = getInverse)
}


## The funtion cacheSolve: If the inverse matrix has already been calculated once it is fetched from
## cache otherwise it is calculated using the function solve.

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'. It is assumed that x is a matrix object generated by
    ## a call to makeCacheMatrix. When we call makeCacheMatrix B is initialized to NULL.
    ## If B is not NULL we have have calculated the inverse before.
    B <- x$getInverse()
    if(!is.null(B)) {
        message("getting cached data")
        return(B)
    }
    ## If B is NULL then we have to calculate the inverse and save it for later using setInverse
    A <- x$get()
    B <- solve(A)
    x$setInverse(B)
    B
}
